// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDYQqXXs0FUdoruuk3Lgbou3SpOMFKZXn4',
    appId: '1:890244852123:web:f0d4fe5a34923d1964993e',
    messagingSenderId: '890244852123',
    projectId: 'cafeteriauide',
    authDomain: 'cafeteriauide.firebaseapp.com',
    storageBucket: 'cafeteriauide.firebasestorage.app',
    measurementId: 'G-GHBMJH2MMM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBNno0hEIOXugaR5Ao4GSytOrScclrIJ5g',
    appId: '1:890244852123:android:49db33bc0fbd294e64993e',
    messagingSenderId: '890244852123',
    projectId: 'cafeteriauide',
    storageBucket: 'cafeteriauide.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDxwINKq4ofxYkjzbwi49C55KxjdEzPn3c',
    appId: '1:890244852123:ios:dc69332a0186ef0364993e',
    messagingSenderId: '890244852123',
    projectId: 'cafeteriauide',
    storageBucket: 'cafeteriauide.firebasestorage.app',
    iosClientId: '890244852123-ep5vm1skfebpqa1iaa8lgm0rr09gd7bi.apps.googleusercontent.com',
    iosBundleId: 'ec.edu.uide.loja.cafeteriaUide',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDxwINKq4ofxYkjzbwi49C55KxjdEzPn3c',
    appId: '1:890244852123:ios:dc69332a0186ef0364993e',
    messagingSenderId: '890244852123',
    projectId: 'cafeteriauide',
    storageBucket: 'cafeteriauide.firebasestorage.app',
    iosClientId: '890244852123-ep5vm1skfebpqa1iaa8lgm0rr09gd7bi.apps.googleusercontent.com',
    iosBundleId: 'ec.edu.uide.loja.cafeteriaUide',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDYQqXXs0FUdoruuk3Lgbou3SpOMFKZXn4',
    appId: '1:890244852123:web:99411d3a688ce65364993e',
    messagingSenderId: '890244852123',
    projectId: 'cafeteriauide',
    authDomain: 'cafeteriauide.firebaseapp.com',
    storageBucket: 'cafeteriauide.firebasestorage.app',
    measurementId: 'G-4T6JFTKE8N',
  );
}
